import {App,h,button,field,select,row,form,modal,table,panel,metrics,money,badge,date,short,dl,download,csv,notice} from './shared.js';
const app=new App({project:'cross-border-clearing',title:'Cross-Border Clearing',abbr:'CB',accent:'#245ab0',tagline:'From payment instruction to settlement.',description:'Submit cross-border payments, price currency conversion, follow each state change, and inspect settlement cycles.',views:[['overview','Overview'],['payments','Payments'],['fx','FX quotes'],['participants','Participants'],['cycles','Settlement cycles'],['activity','Activity']]});
const examples={US:'1002003001',GB:'GB29NWBK60161331926819',DE:'DE89370400440532013000',FR:'FR1420041010050500013M02606',NL:'NL91ABNA0417164300',CH:'CH9300762011623852957',CA:'1234567890',IN:'123456789012',SG:'12345678901',HK:'12345678901',JP:'1234567',AU:'123456789',CN:'123456789012345678'};
function example(p){if(p.country==='MX'){const prefix='9'+p.bic.slice(2,4)+'00000012345678',sum=[...prefix].reduce((n,c,i)=>n+(Number(c)*[3,7,1][i%3])%10,0);return prefix+((10-sum%10)%10);}if(p.country==='BR')return 'BR1500000000000010932840814P2';return examples[p.country]||'';}
function newPayment(){const p=app.data.participants,opts=p.map(x=>[x.bic,`${x.name} · ${x.country} · ${x.currency}`]);const from=select('from','Sending participant',opts),to=select('to','Receiving participant',opts,p.find(x=>x.country==='GB')?.bic||p[1].bic),senderAccount=field('senderAccount','Sender account',{maxLength:34,value:example(p[0])}),beneficiaryAccount=field('beneficiaryAccount','Beneficiary account',{maxLength:34,value:example(p.find(x=>x.country==='GB')||p[1])});const amt=field('amount','Amount in sending currency',{type:'number',step:'.01',min:'.01'}),ccy=h('div',{class:'notice'},'');
 const update=()=>{const f=p.find(x=>x.bic===from.querySelector('select').value),t=p.find(x=>x.bic===to.querySelector('select').value);ccy.textContent=`${f.currency} → ${t.currency}. Account identifiers are validated for ${f.country} and ${t.country}.`;};
 from.querySelector('select').addEventListener('change',()=>{senderAccount.querySelector('input').value=example(p.find(x=>x.bic===from.querySelector('select').value));update();});to.querySelector('select').addEventListener('change',()=>{beneficiaryAccount.querySelector('input').value=example(p.find(x=>x.bic===to.querySelector('select').value));update();});update();
 const d=modal('New cross-border payment',form([row(from,to),ccy,row(field('sender','Sender name',{maxLength:140}),field('beneficiary','Beneficiary name',{maxLength:140})),row(senderAccount,beneficiaryAccount),row(amt,field('reference','End-to-end reference',{maxLength:35,placeholder:'Invoice reference'}))],'Submit payment',async b=>{const result=await app.action('payments',b,'Payment submitted.');d.close();await app.reload();paymentDetail(app.data.payments.find(x=>x.id===result.id)||result);}));}
async function paymentDetail(p){const d=modal('Payment '+short(p.id),dl([['Status',badge(p.state)],['Sender',p.sender],['Beneficiary',p.beneficiary],['Instructed',p.instructed?.value+' '+p.instructed?.currency],['Credited',p.credited?p.credited.value+' '+p.credited.currency:'—'],['Reference',p.reference],['Sending participant',p.debtorAgent],['Receiving participant',p.creditorAgent],['Settlement cycle',p.cycleId||'Pending'],['UETR',h('span',{class:'mono'},p.id)]]),p.reasonText?notice(p.reasonText,p.state==='REJECTED'?'error':''):null,h('h3',{},'Payment history'),h('ol',{class:'timeline'},(p.history||[]).map(e=>h('li',{},h('strong',{},e.toState||e.state||e.to),h('p',{},e.detail||''),h('small',{},date(e.occurredAt))))),button('Download ISO 20022 instruction',async()=>{try{download(await app.request(`payments/${p.id}/message`,{blob:true}),p.id+'.xml');}catch(e){app.toast(e.message,'error');}},'secondary'));
}
async function cycleDetail(c){try{const [positions,transfers]=await Promise.all([app.request(`cycles/${c.id}/positions`),app.request(`cycles/${c.id}/transfers`)]);const d=modal('Settlement cycle #'+c.id,dl([['Status',badge(c.status)],['Payments',c.paymentCount??0],['Gross value',money(c.grossValue)],['Net value',money(c.netValue)],['Liquidity saved',(c.liquiditySavingPct||0)+'%'],['Transfers',c.transferCount??0]]),h('h3',{},'Settlement plan'),table(['From','To','Amount USD','Status'],transfers.map(t=>[t.from,t.to,money(t.amount),badge(t.status)])),h('h3',{},'Participant positions'),table(['Participant','Gross debit','Gross credit','Net'],positions.map(x=>[x.bic,money(x.grossDebit),money(x.grossCredit),money(x.net)])),form([select('bic','Participant statement',app.data.participants.map(p=>[p.bic,p.name]))],'Download camt.053 statement',async b=>{download(await app.request(`cycles/${c.id}/statements/${b.bic}`,{blob:true}),`cycle-${c.id}-${b.bic}.xml`);}));}catch(e){app.toast(e.message,'error');}}
function closeCycle(){const d=modal('Close settlement cycle',notice('Accepted payments in the shared clearing network are netted and settled. A new cycle opens immediately.'),form([],'Close and settle',async()=>{const result=await app.action('cycles/close',{},'Settlement cycle closed.');d.close();await app.reload();cycleDetail(result);}));}
const paymentRows=items=>items.map(p=>[date(p.receivedAt||p.createdAt),p.sender,p.beneficiary,p.instructed?p.instructed.value+' '+p.instructed.currency:p.amount,p.credited?p.credited.value+' '+p.credited.currency:'—',badge(p.state),p.reference,button('Track',()=>paymentDetail(p),'secondary small')]);
app.renderView=(page,d)=>{
 if(page==='payments')return [app.head('Payments','Your payment book, with durable ISO 20022 instructions and timestamped status history.',[button('Export CSV',()=>csv('payments.csv',['UETR','Reference','State','Amount','Currency','Sender','Beneficiary'],d.payments.map(p=>[p.id,p.reference,p.state,p.instructed?.value,p.instructed?.currency,p.sender,p.beneficiary])),'secondary'),button('New payment',newPayment)]),panel('',table(['Received','Sender','Beneficiary','Instructed','Credited','Status','Reference',''],paymentRows(d.payments),'Submit a payment to start tracking it.'))];
 if(page==='fx'){const result=h('div',{});return [app.head('FX quotes','Indicative conversion with a visible spread and quote expiry.'),h('div',{class:'columns equal'},panel('Request a quote',form([row(select('sourceCurrency','From currency',Object.keys(d.rates),'USD'),select('targetCurrency','To currency',Object.keys(d.rates),'GBP')),field('amount','Amount',{type:'number',step:'.01',min:'.01'})],'Get quote',async b=>{const q=await app.action('quotes',b);result.replaceChildren(panel('Quote',dl([['Source',q.source.amount+' '+q.source.currency],['Recipient receives',q.target.amount+' '+q.target.currency],['Settlement value',q.settlement.amount+' '+q.settlement.currency],['Expires',date(q.expiresAt)],['Source rate',q.sourceRate],['Target rate',q.targetRate]]),h('p',{class:'muted'},'Indicative quote. Execution reprices at payment acceptance.')));})),result),panel('Rate board',table(['Currency','Units per USD','Spread'],Object.entries(d.rates).map(([ccy,r])=>[ccy,r.mid,r.spreadBps+' bps'])))];}
 if(page==='participants')return [app.head('Participants','Forty fictional banks across fifteen countries. Positions belong to the shared network.'),panel('',table(['Name','BIC','Country','Currency','Net debit cap USD','Position USD','Queued'],d.participants.map(p=>{const pos=d.dashboard.participants.find(x=>x.bic===p.bic)||{};return[p.name,p.bic,p.country,p.currency,money(p.netDebitCap),money(pos.position),pos.queued||0];}))),button('Process liquidity queue',async()=>{try{const r=await app.action('liquidity/run',{},'Liquidity queue processed.');await app.reload();modal('Liquidity run',dl(Object.entries(r).map(([k,v])=>[k,typeof v==='object'?JSON.stringify(v):v])));}catch(e){app.toast(e.message,'error');}},'secondary')];
 if(page==='cycles')return [app.head('Settlement cycles','Multilateral netting results, settlement instructions, and participant statements.',[button('Close current cycle',closeCycle)]),panel('',table(['Cycle','Status','Payments','Gross USD','Net USD','Saved','Transfers',''],d.dashboard.cycles.map(c=>['#'+c.id,badge(c.status),c.paymentCount??0,money(c.grossValue),money(c.netValue),(c.liquiditySavingPct||0)+'%',c.transferCount??0,button('Inspect',()=>cycleDetail(c),'secondary small')]))),notice('The network is shared. Your payment instructions are private to your workspace; aggregate settlement results are available to network operators.')];
 if(page==='activity')return [app.head('Activity','Your workspace payment and settlement operations.'),app.activity()];
 const t=d.dashboard.totals,saving=t.gross?100*(1-t.net/t.gross):0;
 return [app.head('Overview','Your payment book and the current settlement network.',[button('Refresh',()=>app.reload(),'secondary'),button('New payment',newPayment)]),metrics([['Your payments',d.payments.length,'Private payment book'],['Network settled',Number(t.payments).toLocaleString(),'Payments across settlement cycles'],['Liquidity saved',saving.toFixed(1)+'%','Reduction from gross settlement'],['Queued',d.dashboard.live.queued,'Awaiting liquidity']]),h('div',{class:'columns'},panel('Your recent payments',table(['Received','Sender','Beneficiary','Instructed','Credited','Status','Reference',''],paymentRows(d.payments.slice(0,6)),'Your payment book is empty. Submit your first instruction.')),panel('Current network',dl([['Open cycle','#'+(d.dashboard.openCycle?.id||'—')],['Open cycle payments',d.dashboard.live.open_cycle_payments],['Settlement currency',d.dashboard.settlementCurrency],['Gross settled',money(t.gross)],['Net settled',money(t.net)],['Settlement transfers',t.transfers]]),h('br'),button('Inspect settlement cycles',()=>app.go('cycles'),'secondary')))];
};app.start();
